# Generated by Django 5.1.3 on 2024-12-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_customer_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
